<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/** @var yii\web\View $this */
/** @var common\models\Product[] $products */
/** @var int $activeBasket */
/** @var array $currentItems */

$this->title = 'POS - New Sale';

$productItems = [];
foreach ($products as $product) {
    $productItems[$product->id] = $product->name . ' (stock: ' . $product->stock_quantity . ')';
}

// encode for JS
$productItemsJson = json_encode($productItems);
$currentItemsJson = json_encode($currentItems);

?>
<h1><?= Html::encode($this->title) ?></h1>

<div class="mb-3">
    <strong>Active basket:</strong>
    <?php for ($b = 1; $b <= 3; $b++): ?>
        <?php $btnClass = $b === $activeBasket ? 'btn btn-primary' : 'btn btn-default'; ?>
        <?= Html::a('Basket ' . $b, ['index', 'basket' => $b], ['class' => $btnClass]) ?>
    <?php endfor; ?>
</div>

<p class="text-muted">
    Each basket can hold many products. By default you see 3 rows.
    If customer has more items, click <strong>"+ Add product"</strong>.
</p>

<?php foreach (Yii::$app->session->getAllFlashes() as $type => $message): ?>
    <div class="alert alert-<?= $type === 'error' ? 'danger' : 'success' ?>">
        <?= Html::encode($message) ?>
    </div>
<?php endforeach; ?>

<?php $form = ActiveForm::begin(); ?>

<?= Html::hiddenInput('activeBasket', $activeBasket) ?>

<table class="table table-bordered" id="pos-items-table">
    <thead>
    <tr>
        <th style="width: 40px;">#</th>
        <th>Product</th>
        <th style="width: 120px;">Quantity</th>
        <th style="width: 40px;"></th>
    </tr>
    </thead>
    <tbody>
    <!-- rows will be generated by JS -->
    </tbody>
</table>

<div class="form-group">
    <button type="button" id="btn-add-row" class="btn btn-default">
        + Add product
    </button>
</div>

<div class="form-group">
    <label>Note (payment info)</label>
    <?= Html::textarea('note', '', [
        'class' => 'form-control',
        'rows' => 2,
        'placeholder' => 'Empty = card; or write "cash", "cash+card 50/30", etc.',
    ]) ?>
</div>

<div class="form-group">
    <?= Html::submitButton('Save Basket', [
        'class' => 'btn btn-default',
        'name'  => 'submitType',
        'value' => 'save',
    ]) ?>
    <?= Html::submitButton('Complete Sale', [
        'class' => 'btn btn-primary',
        'name'  => 'submitType',
        'value' => 'sale',
    ]) ?>
</div>

<?php ActiveForm::end(); ?>

<?php
$js = <<<JS
(function() {
    var products = $productItemsJson || {};
    var currentItems = $currentItemsJson || [];
    var tableBody = document.querySelector('#pos-items-table tbody');
    var addBtn = document.getElementById('btn-add-row');
    var maxRows = 100;

    function createRow(index, data) {
        data = data || {};
        var productId = data.product_id || '';
        var quantity  = data.quantity || '';

        var tr = document.createElement('tr');

        // index cell
        var tdIndex = document.createElement('td');
        tdIndex.className = 'row-index';
        tdIndex.textContent = index + 1;
        tr.appendChild(tdIndex);

        // product select
        var tdProduct = document.createElement('td');
        var select = document.createElement('select');
        select.name = 'items[' + index + '][product_id]';
        select.className = 'form-control';

        var optPrompt = document.createElement('option');
        optPrompt.value = '';
        optPrompt.textContent = 'Select product';
        select.appendChild(optPrompt);

        for (var id in products) {
            if (!products.hasOwnProperty(id)) continue;
            var opt = document.createElement('option');
            opt.value = id;
            opt.textContent = products[id];
            if (String(id) === String(productId)) {
                opt.selected = true;
            }
            select.appendChild(opt);
        }

        tdProduct.appendChild(select);
        tr.appendChild(tdProduct);

        // quantity
        var tdQty = document.createElement('td');
        var input = document.createElement('input');
        input.type = 'number';
        input.name = 'items[' + index + '][quantity]';
        input.min = '1';
        input.className = 'form-control';
        if (quantity !== null && quantity !== undefined && quantity !== '') {
            input.value = quantity;
        }
        tdQty.appendChild(input);
        tr.appendChild(tdQty);

        // remove button
        var tdRemove = document.createElement('td');
        tdRemove.className = 'text-center';
        var btn = document.createElement('button');
        btn.type = 'button';
        btn.className = 'btn btn-danger btn-sm btn-remove-row';
        btn.innerHTML = '&times;';
        tdRemove.appendChild(btn);
        tr.appendChild(tdRemove);

        return tr;
    }

    function rebuildIndexes() {
        var rows = tableBody.querySelectorAll('tr');
        rows.forEach(function(row, i) {
            var indexCell = row.querySelector('.row-index');
            if (indexCell) {
                indexCell.textContent = i + 1;
            }
            var select = row.querySelector('select');
            var input  = row.querySelector('input[type="number"]');
            if (select) {
                select.name = 'items[' + i + '][product_id]';
            }
            if (input) {
                input.name = 'items[' + i + '][quantity]';
            }
        });
    }

    function initRows() {
        var initial = currentItems.length > 0 ? currentItems.length : 3; // at least 3 rows
        for (var i = 0; i < initial; i++) {
            var data = currentItems[i] || {};
            var row = createRow(i, data);
            tableBody.appendChild(row);
        }
    }

    addBtn.addEventListener('click', function() {
        var rows = tableBody.querySelectorAll('tr').length;
        if (rows >= maxRows) {
            alert('Too many items in one sale.');
            return;
        }
        var row = createRow(rows, {});
        tableBody.appendChild(row);
    });

    tableBody.addEventListener('click', function(e) {
        if (e.target && e.target.classList.contains('btn-remove-row')) {
            var row = e.target.closest('tr');
            if (row) {
                tableBody.removeChild(row);
                rebuildIndexes();
            }
        }
    });

    // init on load
    initRows();
})();
JS;

//$this->registerJs(\yii\web\View::POS_END, $js);
$this->registerJs($js, \yii\web\View::POS_END);

?>
